### ISSUE TITLE
Display on/off

### ISSUE THREAD

**Issue by dmijango** [georgezhao2010/midea_ac_lan#21]
Thank you very much for this great plugin. 
Is it possible that the display can be turned on/off with a switch?

**Comment by georgezhao2010** [comment]
> Thank you very much for this great plugin. Is it possible that the display can be turned on/off with a switch?

Maybe in the future

**Comment by sarahmva** [comment]
This would be great to have! Thanks for all your work.

**Comment by Oligarch** [comment]
Also interested in this feature

**Comment by tommy2d** [comment]
This would indeed be a great feature! The very bright screen is keeping me from sleeping in as we speak!

**Comment by georgezhao2010** [comment]
Screen display switch is realized in version 0.2.x

**Comment by tommy2d** [comment]
Thanks! Works like a charm!

**Comment by sarahmva** [comment]
I did notice that the switch in Home Assistant turns back on after a few seconds even though the display stays off. 

1. Screen Display Switch is ON, Display on AC is on.
2. I turn off the Screen Display Switch in HA
3. Display on AC unit turns off
4. 3 seconds later, the Screen Display Switch in HA turns back on.
5. Display stays off.

Not a big problem, I was just wondering if this is intentional.
