### ISSUE TITLE
Advantages

### ISSUE THREAD

**Issue by pathia** [georgezhao2010/midea_ac_lan#22]
Hi,
Could you please elaborate on what the advantages are compared to the mac-zhou midea-ac-py repo?
I currently use that and am honestly curious as to what the advantages would be.

**Comment by georgezhao2010** [comment]
> Hi, Could you please elaborate on what the advantages are compared to the mac-zhou midea-ac-py repo? I currently use that and am honestly curious as to what the advantages would be.

- No need to install extra python libs.
- Automated device discover and configuration based HA config flow UI.
- Extra sensors and swithes
- Synchronize status with the device by long TCP connection in time.
- More control protocols supported.

**Comment by mill1000** [comment]
The first bullet should not be considered an advantage. In fact, it's a violation of a [HomeAssistant "rule".](https://developers.home-assistant.io/docs/creating_platform_index/#interfacing-with-devices)

Config flow UI is a great feature. mac-zhou/midea-ac-py recently gained support for the config flow UI as well. Along with additional sensor entities and there is a PR out for some additional switches.

Automated device discovery is a great feature. I would like to see that in mac-zhou/midea-ac-py as well.

I imagine it would be better for everyone if we worked together instead of duplicating our efforts in different projects.
