### ISSUE TITLE
Top Load Washer 38030165(None) 制造商：Midea

### ISSUE THREAD

**Issue by 2331892928** [georgezhao2010/midea_ac_lan#279]
This device can be added to ha, but:
Out of control;
After the washing machine is controlled by the Huawei app, the ha can synchronize the status, but the synchronization rate is low and almost not synchronized

**Comment by georgezhao2010** [comment]
> 

Enable the debug log of midea_ac_lan and log for a while, then post the log out.

**Comment by georgezhao2010** [comment]
I haven't got more infomation for a long time. This issue may be caused by your washer not actively sending information when its status changes. In this case, if you want to shorten the synchronization time, you can only shorten the interval for actively refreshing the status, which is located in `Settings -> Devices & Services -> Midea AC LAN -> Device -> CONFIGURE`. The refresh interval can be set to a minimum of 1 second, but honestly, I don’t recommend you do this unless the update of the washer’s status is really important to you.
